# Page settings

baseurl = "/"
languageCode = "en-us"
title = "John Doe Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Viviane Girardin"
        tagline = "M.Sc. Toxicology"
        avatar = "Orbit.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: girardin.vivi@gmail.com"
        title = "girardin.vivi@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+4797944071"
        title = "+4797944071"

       #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//portfoliosite.com"
        #title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/viviane-girardin"
        title = "linkedin.com/in/viviane-girardin"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/vivigirardin"
        title = "github.com/vivigirardin"

       # [[params.contact.list]]
      #  class = "twitter"
       # icon = "fa-twitter"
        #url = "//twitter.com/username"
        #title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Toxicology"
        college = "University of Oslo"
        dates = "January 2017 - December 2018"

        [[params.education.list]]
        degree = "BSc in Biologi"
        college = "University of Oslo"
        dates = "August 2014 - December 2016"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Portuguese"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "Norwegian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "R"

        [[params.interests.list]]
        interest = "Python"

        [[params.interests.list]]
        interest = "Git"
        
        [[params.interests.list]]
        interest = "Travel"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "I am a new graduate with a Master's degree in toxicology from the University of Oslo. My master's thesis was about the origin and bioaccumulation of organic pollutants from traffic in dragonfly larvae. My Master's thesis was funded by the Norwegian Public Roads Administration and the Norwegian Institute for Water Research (NIVA). Last summer, I worked in the section for climate and environment at Statens vegvesen (the Norwegian Public Roads Administration). Previously, I worked as a research assistant at NIVA. The collaboration with NIVA continues, and I was hired to summarize my thesis for publication in a scientific journal. As a person, I am solution-oriented, committed and creative. I am also a hardworking and goal-oriented person who, among other things, continues with the studies without postponement despite the fact that I have become the mother of my second child in the middle of my studies."
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2019 - Present"
        company = "Norwegian Institute for Water Research (NIVA)"
        details = " Writing of scientific article, laboratory work, data management."

        [[params.jobs.list]]
        position = "Summer intern"
        dates = "May 2018 - August 2018"
        company = "Statens vegvesen"
        details = "Field work. \n\n Wrote a report on the effects of suspended particles in aquatic systems, wrote a summary for the report “Sustainable Design and Maintenance of Stormwater Treatment Facilities”. \n\n Diverse literature research."

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "January 2016 - August 2016"
        company = "Norwegian Institute for Water Research (NIVA)"
        details = "Laboratory work: Extraction methods for chemical analysis of organic and inorganic compounds in fish, phytoplankton and sediment and quantification using HPLC."

        [[params.jobs.list]]
        position = "Administrative Officer (Temporary contract)"
        dates = "June 2014 - January 2015"
        company = "Brazilian – Norwegian Chamber of Commerce"
        details = "Administrative support. \n\n Organized, managed and represented BNCC on events. \n\n Webmaster for BNCC’s website."



    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Courses 6 Other Experiences"
       # intro = "**You can list your side projects or open source libraries in this section."

        [[params.projects.list]]
        position = "**Experience -**Teaching assistant and interim board member"
        dates = "January 2019 - Present"
        company = "Carpentry@UiO"
        details = "Carpentry@UiO offers foundational coding and data science skills workshops to PhD students, researchers and others at UiO. **Volunteering work**"

    
        [[params.projects.list]]
        position = "**Experience -** Teaching assistant and interim board member"
        dates = "January 2019 - Present"
        company = "Carpentry@UiO"
        details = "Carpentry@UiO offers foundational coding and data science skills workshops to PhD students, researchers and others at UiO. **Volunteering work**."
        
        [[params.projects.list]]
        position = "**Experience -** Board member"
        dates = "2017 - Present"
        company = "Sameiet Kirkeveien 129b"
        details = "The Board members are responsible for making decisions regarding the maintenance of building, and set and enforce the house rules.**Volunteering work**"
  
        [[params.projects.list]]
        position = "**Experience -**Swimming instructor"
        dates = "May 2018 - Present"
        company = "Norges Livredningsselskap"
        details = "Swimming courses for children between 4 and 12 years-old."

        [[params.projects.list]]
        position = "**Course -**Norges Kurs i arbeidsvarsling i henhold til Statens vegvesen Håndbok N301."
        dates = "1-day course , 2018"
        company = "Statens vegvesen"
        details = "Course for those who work on or by the roadside. It gives the necessary knowledge and understanding of their own and others' safety when working on or by road, and the formal safety procedures that must be followed before and during the work."

        #url = "https://arbeidsvarsling.smartlearn.no/course-category/course-1"
       
        [[params.projects.list]]
        position = "**Course -**International General Certification in Occupational Health and Safety"
        dates = "Approx. 135h , 2012"
        company = "National Examination Board in Occupational HSE (NEBOSH)"
        details = "The course incudes the practical assessment of a workplace. **Passed with distinction**."

        [[params.projects.list]]
        position = "**Course -**Experimental animal studies"
        dates = "Approx. 135h , 2012"
        company = "National Examination Board in Occupational HSE (NEBOSH)"
        details = "The course incudes 25 hours of practical work at an animal facility."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills"

        [[params.skills.list]]
        skill = "R"
        enable = true
        icon = "fa-rocket"
                
        [[params.skills.list]]
        skill = "Python"
        #level = "98%"

        [[params.skills.list]]
        skill = "GitHub"
        #level = "95%"


        [[params.skills.list]]
        skill = "Photoshop"
        #level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "2019 Viviane Girardin"
