# Page settings

baseurl = "/"
languageCode = "en-us"
title = "John Doe Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Viviane Girardin"
        tagline = "M.Sc. Toxicology"
        avatar = "Orbit.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: girardin.vivi@gmail.com"
        title = "girardin.vivi@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+4797944071"
        title = "+4797944071"

       #[[params.contact.list]]
        #class = "website"
        #icon = "fa-globe"
        #url = "//portfoliosite.com"
        #title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/viviane-girardin"
        title = "linkedin.com/in/viviane-girardin"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/vivigirardin"
        title = "github.com/vivigirardin"

       # [[params.contact.list]]
      #  class = "twitter"
       # icon = "fa-twitter"
        #url = "//twitter.com/username"
        #title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc in Toxicology"
        college = "University of Oslo"
        dates = "January 2017 - December 2018"

        [[params.education.list]]
        degree = "BSc in Biology"
        college = "University of Oslo"
        dates = "August 2014 - December 2016"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "**Portuguese** - Native <br> **Norwegian** - Professional <br> **English** - Professional"
        


    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "**R** - advanced <br> **Python** - basic <br> **HTML** - basic <br> **GitHub** - intermediate <br> **Photoshop** - intermediate <br> **Excel** - intermediate"
      
# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    #use """ text """ instead of "text" to avoid having a long string of text

    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """<font size="+1">**Mature new graduate with work
        experience** </font>.<br><br> 
        <ul>
        <li>**Laboratory and field work experience** working with a variety of instruments for
        collection,extraction and analysis of organic and inorganic contaminants in water, sediment
        and biota.</li>
        <li>**Solid computer skills** such as programming and 
        markup languages **Python, R, HTML and Markdown** (this page was created using 
        most of these languages). </li>
        <li>**Customer service** experience in several countries</li>
        </ul>
        <br><font size="+1">**According to previous employers:**</font><br><br>
        <center><q><i>She works efficiently, systematically and independently and is not afraid of
        challenges. She... has solved all the tasks she was given 
        in a very competent manner.</q></i> <br>
        <a href= "https://www.dropbox.com/s/cz2ohpempp7gblr/2018.09.21_Statens_vegvesen_Sluttattest_for_sommerjobb_2018.pdf?dl=0" 
        style="color: #0000EE">Kjersti Wike Kronvall (Statens vegvesen)</a><br><br>
        <i><q>My experience with Viviane proved she was reliable, responsive, 
        responsible, and used her initiative. She always produced what was 
        required in a timely manner; normally making the delivery ahead of the agreed timeline. 
        She is not afraid to ask questionsas she grows into 
        the task assigned her.</q></i><br>
        <a href = "https://www.dropbox.com/s/ceognfnmt15uo0t/Aker_Sol_Ref.pdf?dl=0"style="color: #0000EE">Timothy Canty (Aker Solutions)</a><br><br>
        <i><q>Viviane proved to be a very loyal member...and she also showed initiative and 
        made new suggestions for improvement, both in the administrative and data 
        related part of the work. Viviane demonstrated a structured approach.</q></i>
        <br><a href= "https://www.dropbox.com/s/tmlnhnt3hrgycl8/BNCC_Ref.pdf?dl=0" style="color: #0000EE">Harald Martinsen (Brazilian-Norwegian Chamber of Commerce)<center/></a>
      
        """
    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Work Experience"

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "2019 - Present"
        company = "Norwegian Institute for Water Research (NIVA)"
        details = "Elaboration of scientific article (in progress), laboratory work."

        [[params.jobs.list]]
        position = "Summer intern"
        dates = "May 2018 - August 2018"
        company = "Statens vegvesen"
        details = "Field work. <br> Elaboration of a report on the effects of suspended particles in aquatic systems, wrote a summary for the report “Sustainable Design and Maintenance of Stormwater Treatment Facilities”. <br> Diverse literature research."

        [[params.jobs.list]]
        position = "Research Assistant"
        dates = "January 2016 - August 2016"
        company = "Norwegian Institute for Water Research (NIVA)"
        details = "Laboratory work: Extraction methods for chemical analysis of organic and inorganic compounds in fish, phytoplankton and sediment and quantification using HPLC."

        [[params.jobs.list]]
        position = "Administrative Officer (Temporary contract)"
        dates = "June 2014 - January 2015"
        company = "Brazilian – Norwegian Chamber of Commerce"
        details = "Administrative support. <br> Organization, management and representation of BNCC on monthly events. <br> Re-designed and re-structured the whole BNCC’s website."



    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Courses 6 Other Experiences"
       # intro = "**You can list your side projects or open source libraries in this section."


        [[params.projects.list]]
        position = "**Volunteering work -** Teaching assistant and <br>interim board member"
        dates = "January 2019 - Present"
        company = "Carpentry@UiO"
        details = """Carpentry@UiO offers foundational coding and data 
        science skills workshops to PhD students, researchers and others 
        at UiO"""
        
        [[params.projects.list]]
        position = "**Volunteering work -** Board member"
        dates = "2017 - Present"
        company = "Sameiet Kirkeveien 129b"
        details = "The Board members are responsible for making decisions regarding the maintenance of building, and set and enforce the house rules.**Volunteering work**"
  
        [[params.projects.list]]
        position = "**Experience -**Swimming instructor"
        dates = "May 2018 - Present"
        company = "Norges Livredningsselskap"
        details = "Swimming courses for children between 4 and 12 years-old."

        [[params.projects.list]]
        position = """<a href ="https://arbeidsvarsling.smartlearn.no/course-category/course-1" style="color:#0000EE" >
        **Course -**</a>Norges Kurs i arbeidsvarsling i henhold til <br> Statens vegvesen Håndbok N301."""
        dates = "1-day course , 2018"
        company = "Statens vegvesen"
        details = """Course aimed on safery during roadwork. 
        It gives the necessary knowledge and understanding of their 
        own and others' safety when working on or by road, and the 
        formal safety procedures that must be followed before and 
        during the work."""

        #url = "https://arbeidsvarsling.smartlearn.no/course-category/course-1"
       
        [[params.projects.list]]
        position = "**Course -**International General Certification <br> in Occupational Health and Safety"
        dates = "Approx. 135h , 2012"
        company = "National Examination Board in Occupational HSE (NEBOSH)"
        details = "The course incudes the practical assessment of a workplace. **Passed with distinction**."

        [[params.projects.list]]
        position = "**Course -**Experimental animal studies"
        dates = "April 2018"
        company = "University of Oslo"
        details = "The course incudes 25 hours of practical work at an animal facility."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills"

        [[params.skills.list]]
        skill = "R, GitHub, travel"
        

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Viviane Girardin"
